config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :parents
  # root to: "home#index"
  devise_for :professionals

  resources :specialties
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/specialty.rb
class Specialty < ApplicationRecord
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  before_action :set_specialty, only: %i[ show edit update destroy ]

  # GET /specialties or /specialties.json
  def index
    @specialties = Specialty.all
  end

  # GET /specialties/1 or /specialties/1.json
  def show
  end

  # GET /specialties/new
  def new
    @specialty = Specialty.new
  end

  # GET /specialties/1/edit
  def edit
  end

  # POST /specialties or /specialties.json
  def create
    @specialty = Specialty.new(specialty_params)

    respond_to do |format|
      if @specialty.save
        format.html { redirect_to specialty_url(@specialty), notice: "Specialty was successfully created." }
        format.json { render :show, status: :created, location: @specialty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialties/1 or /specialties/1.json
  def update
    respond_to do |format|
      if @specialty.update(specialty_params)
        format.html { redirect_to specialty_url(@specialty), notice: "Specialty was successfully updated." }
        format.json { render :show, status: :ok, location: @specialty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @specialty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialties/1 or /specialties/1.json
  def destroy
    @specialty.destroy

    respond_to do |format|
      format.html { redirect_to specialties_url, notice: "Specialty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialty
      @specialty = Specialty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def specialty_params
      params.require(:specialty).permit(:name)
    end
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/specialties/_form.html.erb
<%= form_with(model: specialty, local: true) do |form| %>
  <% if specialty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(specialty.errors.count, "error") %> prohibited this specialty from being saved:</h2>

      <ul>
        <% specialty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/specialties/edit.html.erb
<h1>Editing Specialty</h1>

<%= render 'form', specialty: @specialty %>

<%= link_to 'Show', @specialty %> |
<%= link_to 'Back', specialties_path %>

app/views/specialties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Specialties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialties.each do |specialty| %>
      <tr>
        <td><%= specialty.name %></td>
        <td><%= link_to 'Show', specialty %></td>
        <td><%= link_to 'Edit', edit_specialty_path(specialty) %></td>
        <td><%= link_to 'Destroy', specialty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specialty', new_specialty_path %>

app/views/specialties/new.html.erb
<h1>New Specialty</h1>

<%= render 'form', specialty: @specialty %>

<%= link_to 'Back', specialties_path %>

app/views/specialties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @specialty.name %>
</p>

<%= link_to 'Edit', edit_specialty_path(@specialty) %> |
<%= link_to 'Back', specialties_path %>